# Makefile - makefile for apps/vi/vw_curses
#
# modification history
# --------------------
# 01d,07jan04,jn   Don't use rules.library within target/usr/apps
# 01c,12nov03,job  Changed TGT_DIR to WIND_USR 
# 01b,22sep03,job  Modified to make RTP version
# 01a,22aug03,md   created
#
# DESCRIPTION
# This file contains the makefile rules for building the curses library
#
#

SUBDIRS = curses termlib test

include $(WIND_USR)/make/rules.rtp
