# Makefile - makefile for src/demo/vi
#
# modification history
# --------------------
# 01c,07jan04,jn   Don't use rules.library within target/usr/apps
# 01b,12nov03,job  Changed TGT_DIR to WIND_USR
# 01a,22aug03,md   created
#
# DESCRIPTION
# This file contains the makefile rules for building the vi binary
#
#

SUBDIRS = vw_curses aclock

include $(WIND_USR)/make/rules.rtp
